stages:
  - check-codestyle
  - build

<<<<<<< HEAD
before_script:
  - apt-get update && apt-get install -y libncurses5-dev libncursesw5-dev
||||||| parent of 2109a96 (Change gitlab-ci.yml: add install libncurses in CI)
.build-script:
  script:
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."
=======
stages:
  - check-codestyle
  - build

before_script:
  - apt-get update && apt-get install -y libncurses5-dev libncursesw5-dev
>>>>>>> 2109a96 (Change gitlab-ci.yml: add install libncurses in CI)

.check-codestyle:
  script:
    - echo "Check codestyle..."
    - git ls-files *.{cpp,h} | xargs clang-format -i --verbose && git diff --exit-code
    - echo "Codestyle is fine."

.build-script:
  script:
    - echo "Compiling the code..."
    - make
    - echo "Compile complete."

checkstyle:
  stage: check-codestyle
  extends: .check-codestyle

build:
  stage: build
  extends: .build-script