image: registry.csc.sibsutis.ru/ci/git-clang-format:latest

stages:
  - check-format
  - build
  - test

check-format:
  stage: check-format
  script: 
    - find . -type f -name '*.[ch]' | xargs clang-format -i --verbose
    - git diff --exit-code

build:
  stage: build
  script:
    - apt-get update
    - apt-get install -y libncurses5-dev libncursesw5-dev
    - make

test:
  stage: test
  script:
    - apt-get update
    - apt-get install -y libncurses5-dev libncursesw5-dev
    - make
    - make test